source 'https://rubygems.org'

gem 'faraday', '~> 2.14'
gem 'faraday-retry', '~> 2.4'
gem 'propshaft'
gem 'puma', '>= 5.0'
gem 'rails', '~> 8.1.2'
gem 'rswag-api', '~> 2.17'
gem 'rswag-ui', '~> 2.17'
gem 'tzinfo-data', platforms: %i[windows jruby]

group :development do
  gem 'pry-rails', '~> 0.3.11'
end

group :test do
  gem 'factory_bot_rails', '~> 6.5'
  gem 'simplecov', '~> 0.22.0', require: false
  gem 'webmock', '~> 3.26'
end

group :development, :test do
  gem 'debug', platforms: %i[mri windows], require: 'debug/prelude'
  gem 'pry', '~> 0.16.0'
  gem 'pry-byebug', '~> 3.12'
  gem 'rspec-rails', '~> 8.0'
  gem 'rswag-specs', '~> 2.17'
end

