source 'https://rubygems.org'

gem 'faraday', '~> 2.14'
gem 'faraday-retry', '~> 2.4'
gem 'propshaft'
gem 'puma', '>= 5.0'
gem 'rails', '~> 8.1.2'
gem 'tzinfo-data', platforms: %i[windows jruby]

group :development do
  gem 'pry-rails', '~> 0.3.11'
end

group :test do
  # gem 'rspec', '~> 3.13'
  # gem 'factory_bot_rails', '~> 6.2'
  # gem 'faker', '~> 3.2'
end

group :development, :test do
  # gem 'rspec-rails', '~> 8.0
  gem 'debug', platforms: %i[mri windows], require: 'debug/prelude'
  gem 'pry', '~> 0.16.0'
  gem 'pry-byebug', '~> 3.12'
end
